name: driverslicenses
description: A new Flutter project.

version: 1.0.2+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  http: ^0.12.0+2
  flutter_custom_clippers: ^0.1.6
  html_unescape: ^1.0.1+2
  auto_size_text: ^2.0.0+2
  shared_preferences: ^0.4.2
  flutter_launcher_icons: ^0.7.4
  provider: 4.3.2+2


  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_ios: 'assets/images/icon.png'
  image_path_android: 'assets/images/icon.png'
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/langs/en.json
    - assets/langs/es.json
    - assets/license/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300